#!/usr/bin/env php
<?php

use Endsides\Css\Declaration;
use Endsides\Html\Attribute;

require_once __DIR__ . '/src/autoload.php';

$messages = [];

$declaration = new Declaration('color', 'red', true);

if ($declaration->getProperty() !== 'color') {
	$messages['failure'][] = 'Declaration property is not set correctly';
}
else {
	$messages['success'][] = 'Declaration property is set correctly';
}

if ($declaration->getValue() !== 'red') {
	$messages['failure'][] = 'Declaration value is not set correctly';
}
else {
	$messages['success'][] = 'Declaration value is set correctly';
}

if (!$declaration->isImportant()) {
	$messages['failure'][] = 'Declaration is not marked as important';
}
else {
	$messages['success'][] = 'Declaration is marked as important';
}

$attribute = new Attribute('style', 'color: red !iimportant;');

if ($attribute->getName() !== 'style') {
	$messages['failure'][] = 'Attribute name is not set correctly';
}
else {
	$messages['success'][] = 'Attribute name is set correctly';
}

if ($attribute->getValue() !== 'color: red !important;') {
	$messages['failure'][] = 'Attribute value is not set correctly';
}
else {
	$messages['success'][] = 'Attribute value is set correctly';
}


foreach ($messages as $type => $_messages) {
	foreach ($_messages as $message) {
		if ($type === 'success') {
			echo "\033[1;32m ✔";
		}
		elseif ($type === 'failure') {
			echo "\033[1;31m ✘";
		}
		elseif ($type === 'warning') {
			echo "\033[1;33m ⚠";
		}
		elseif ($type === 'info') {
			echo "\033[1;34m ℹ";
		}
		elseif ($type === 'debug') {
			echo "\033[1;35m ⚙";
		}
		echo " {$message}\033[0m" . PHP_EOL;
	}
}

if (!empty($messages['failure'])) {
	echo "\x07";
	exit(1);
}
exit(0);
