#!/usr/bin/env php
<?php

use Endsides\Unit\Tester;
use Endsides\Unit\CssDeclarationTester;
use Endsides\Unit\CssDeclarationBlockTester;
use Endsides\Unit\CssSelectorTester;
use Endsides\Unit\HtmlAttributeTester;

require_once __DIR__ . '/src/autoload.php';

$declarationTester = new CssDeclarationTester();
$declarationTester->test();

$declarationBlockTester = new CssDeclarationBlockTester();
$declarationBlockTester->test();

$selectorTester = new CssSelectorTester();
$selectorTester->test();

$attributeTester = new HtmlAttributeTester();
$attributeTester->test();

Tester::run();
