#!/usr/bin/env php
<?php

use Endsides\Test\Tester;
use Endsides\Test\CssDeclarationTester;
use Endsides\Test\HtmlAttributeTester;

require_once __DIR__ . '/src/autoload.php';

$declarationTester = new CssDeclarationTester();
$declarationTester->test();

$attributeTester = new HtmlAttributeTester();
$attributeTester->test();

Tester::run();
