#!/usr/bin/env php
<?php

use Endsides\Common\Tester;

$autoloader = require_once __DIR__ . '/src/autoload.php';

Tester::performTestsFrom($autoloader->getDirectory() . 'Unit', $autoloader->getNamespace() . 'Unit');

Tester::displayResults();
